### ISSUE TITLE
Issue with `Dockerfile`

### ISSUE THREAD

**Issue by lupionpe** [DroneDB/Server#12]
### What is the problem?

I modified the dependencies referencing a forked version of DroneDB/Hub, when trying to re-run the `Dockerfile`, I run into an issue of:

```
The command '/bin/sh -c cd /server/vendor/ddb && npm install --production && npm install nan && npm install -g cmake-js && CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) cmake-js compile --prefer-make' returned a non-zero code: 1
```

There are a lot more errors `toInt64()` and `Value& Value::operator=(const Value& rhs)`.

### What should be the expected behavior?

To build correctly so I can run this new docker image via `ddb-server.sh`.

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

Remove the dependency of DroneDB/Hub and add blk-app/hub.

**Comment by pierotofy** [comment]
> I modified the dependencies referencing a forked version of DroneDB/Hub

I can't provide advice on a version of Server that's been modified :pray:
