### ISSUE TITLE
ddb-server.sh not deploying

### ISSUE THREAD

**Issue by goodshort** [DroneDB/Server#3]
### What is the problem?

[Latest commit on ddb-server.sh](https://github.com/DroneDB/Server/commit/1fc87929d5d60fb33fe083da0b0d72de655bb766#diff-78228f96c5f98c3c13fa563730d2cb2c758d24e3dde5b41232c7981886d9af96) made the installation impossible. The script will spit out a blank line.

I suspect the `Exit 1` line [here](https://github.com/DroneDB/Server/blob/1fc87929d5d60fb33fe083da0b0d72de655bb766/ddb-server.sh#L71) was set for testing purpose and not removed when pushed.

### What should be the expected behavior?

It is expected that the installation will start, or at least give an output to the user.

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

One can reproduce this issue right now by following the steps on the [dronedb download page](https://docs.dronedb.app/download.html#server).

```
curl -fsSL https://raw.githubusercontent.com/DroneDB/Server/master/ddb-server.sh -o ddb-server.sh
chmod +x ddb-server.sh
./ddb-server.sh
```

### Workaround

Used the previous version of the script on the steps above

` curl -fsSL https://raw.githubusercontent.com/DroneDB/Server/f9f9d2a68c0af2b719d93389db5c64855b8dff81/ddb-server.sh -o ddb-server.sh`

**Comment by pierotofy** [comment]
Ups! Thanks for the report. A debug line was mistakenly committed that was making the script exit prematurely.

Should be fixed now!
