### ISSUE TITLE
Public repo created is not public

### ISSUE THREAD

**Issue by coumbsek** [DroneDB/Server#4]
### What is the problem?

After creating a public repo you land on the datasets page and all seems good.
But if you refresh the page you constat that the repo is indeed private.
You have to edit its properties to make it public really.

### What should be the expected behavior?

If public option selected during creation the repo should be public for true.

### How can we reproduce this? (What steps did you do to trigger the problem? Be detailed)

Create a public repo and refresh the dataset page.

**Comment by pierotofy** [comment]
Hi @coumbsek :wave: thanks for the report!

This should be fixed with the latest version (1.0.1). Feel free to re-open if the issue persists? :pray:
